### ISSUE TITLE
Compatibility with ESP8266 arduino ide

### ISSUE THREAD

**Issue by dmason1992** [PaulStoffregen/NewPing#4]
I get the following error when trying to compile the newPingExample (the single sensor one).

```
In file included from NewPingExample.ino:5:0:
D:\Users\Dropbox\Arduino\libraries\NewPing/NewPing.h:113:20: fatal error: avr/io.h: No such file or directory
 #include <avr/io.h>
                    ^
compilation terminated.
Error compiling.
```

Obviously the avr libraries aren't applicable for ESP8266 but I can't work out the equivalent from esp8266 for the swap.

**Comment by thejester88** [comment]
What IDE of the arduino ide are you running? 
Make sure you have the library in the correct folder.

**Comment by PaulStoffregen** [comment]
Please understand this github repository is *only* for a specific Teensy modification.

The official NewPing library by Tim Eckel is hosted on Bitbucket.  Please find it here:
https://bitbucket.org/teckel12/arduino-new-ping/wiki/Home

This is *not* the place to report issues, other than problems specific to Teensy.  For all other boards, please comment on Tim's repository at Bitbucket.
