### ISSUE TITLE
Hc-sr04 inaccurate even with median

### ISSUE THREAD

**Issue by Tarcontar** [PaulStoffregen/NewPing#7]
Hi, I wonder if you could implement a function to return the measured distance in mm and also take the temperature into account. I need for my Projekt a bit more accuracy.

Regards Tarcontar

**Comment by PaulStoffregen** [comment]
Sorry, this isn't the right place to ask.

In fact, it's just a leftover copy of NewPing, which I made long ago when adding a tiny change.
